### ISSUE TITLE
close??

### ISSUE THREAD

**Issue by urmoomisgay** [Not-Cyrus/GoRaider#1]
everytime i open it will open cmd and close it?

**Comment by Not-Cyrus** [comment]
put your bot token in LoginInfo.json and change the "GuildID" to the guildID you want to nuke 

your JSON file should look like:
`{
	"Token": "Bot yourbotstokenhere",
	"GuildID": "751963149793383465"
}` but replace with your stuff obviously

Contact me here: !fishgang Cy#8242 for further questions

**Comment by Not-Cyrus** [comment]
Closed as there has been no response for 19 hours, If you need further support contact me here: !fishgang Cy#8242
